title: "Matheus Monteiro Nascimento"
email: "matheus.monteiro_nascimento@leuphana.de"
description: "Professional website for Mont Nasc â€” research, publications, teaching, news, contact."
baseurl: ""
url: "https://montnasc.github.io"
theme: minima
markdown: kramdown
paginate: 5